LINQ-STD/Models/Context.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Drawing.Printing;
using System.Linq;
using System.Web;

namespace LINQ_STD.Models
{
    public class Context : DbContext
    {
        public DbSet<Student>Students { get; set; }
        public DbSet<Note>Notes { get; set; }
        public DbSet<Lesson>Lessons { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
        }
    }
}

LINQ-STD/Models/Lesson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LINQ_STD.Models
{
    public class Lesson
    {
        [Key]
        public int Lesson_Id { get; set; }
        [StringLength(50)]
        public string Lesson_Name { get; set; }
        public ICollection<Note> Notes { get; set; }
    }
}

LINQ-STD/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LINQ_STD.Models
{
    public class Note
    {
        [Key]
        public int Note_Id { get; set; }
        public int Note_Average { get; set; }
        public int Note_1 { get; set; }
        public int Note_2 { get; set; }
        public bool Statu { get; set; }
        public int Lesson_Id { get; set; }
        public virtual Lesson Lesson { get; set; }


        public int Student_Number { get; set; }
        public virtual Student Student { get; set; }
    }
}

LINQ-STD/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LINQ_STD.Models
{
    public class Student
    {
        [Key]
        public int Student_Number { get; set; }

        [StringLength(50)]
        public string Student_Name { get; set; }

        [StringLength(50)]
        public string Student_Surname { get; set; }
        public ICollection<Note> Notes { get; set; }
    }
}

LINQ-STD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LINQ_STD.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LINQ-STD/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LINQ_STD.Models;

namespace LINQ_STD.Controllers
{
    public class LessonController : Controller
    {
        Context c = new Context();
        public ActionResult Lesson_Index()
        {
            var control = c.Lessons.ToList();
            return View(control);
        }
        public ActionResult Add_Lesson()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add_Lesson(Lesson l)
        {
            c.Lessons.Add(l);
            c.SaveChanges();
            return RedirectToAction("Lesson_Index");
        }
        public ActionResult Delete_Lesson (int id){
            var control = c.Lessons.Find(id);
            c.Lessons.Remove(control);
            c.SaveChanges();
            return RedirectToAction("Lesson_Index");
        }
        [HttpGet]
        public ActionResult Update_Lesson(int id) {
            var lesson = c.Lessons.Find(id);
            return View(lesson);
        }
        [HttpPost]
        public ActionResult Update_Lesson(Lesson lesson) {
            var l = c.Lessons.Find(lesson.Lesson_Id);
            l.Lesson_Name = lesson.Lesson_Name;
            l.Lesson_Id = lesson.Lesson_Id;
            c.SaveChanges();
            return RedirectToAction("Lesson_Index");
        }
    }
}

LINQ-STD/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LINQ_STD.Models;
using System.Web.Mvc;

namespace LINQ_STD.Controllers
{
    public class NoteController : Controller
    {
        Context c = new Context();
        public ActionResult Note_Index()
        {
            var notes = c.Notes.ToList();
            return View(notes);
        }
        public ActionResult Add_Note (){ 
        return View();
        }
        [HttpPost]
        public ActionResult Add_Note(Note n) {
            n.Note_Average = (n.Note_1 + n.Note_2) / 2;
            if (n.Note_Average >= 50)
                n.Statu = true;
            else
                n.Statu = false;
            c.Notes.Add(n);
            c.SaveChanges();
            return RedirectToAction("Note_Index"); 
        }
        public ActionResult Delete_Note(int id){
            var control = c.Notes.Find(id);
            c.Notes.Remove(control);
            c.SaveChanges();
            return RedirectToAction("Note_Index");
        }
        public ActionResult Update_Note(int id) {
            var n = c.Notes.Find(id);
            return View(n);
        }
        [HttpPost]
        public ActionResult Update_Note(Note n) {
            var new_n = c.Notes.Find(n.Note_Id);
            new_n.Note_1 = n.Note_1;
            new_n.Note_2 = n.Note_2;
            
            new_n.Student_Number = n.Student_Number;
            new_n.Lesson_Id = n.Lesson_Id;
            new_n.Note_Average=(new_n.Note_1+new_n.Note_2)/ 2;
            if (new_n.Note_Average >= 50)
                new_n.Statu = true;
            else
            {
                new_n.Statu = false;
            }
            c.SaveChanges();
            return RedirectToAction("Note_Index");
        }
        
    }
} 

LINQ-STD/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LINQ_STD.Models;

namespace LINQ_STD.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        Context c = new Context();
        public ActionResult Student_Index()
        {
            var control = c.Students.ToList();
            return View(control);
        }
        [HttpGet]
        public ActionResult Add_Student()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add_Student(Student s)
        {
            c.Students.Add(s);
            c.SaveChanges();
            return RedirectToAction("Student_Index");
        }
        public ActionResult Delete_Student(int id)
        {
            var s = c.Students.Find(id);
            c.Students.Remove(s);
            c.SaveChanges();
            return RedirectToAction("Student_Index");
        }
        [HttpGet]
        public ActionResult Update_Student(int id)
        {
            var s = c.Students.FirstOrDefault(x=>x.Student_Number==id);
            
            return View(s);
        }
        [HttpPost]
        public ActionResult Update_Student(Student s)
        {
            var new_s = c.Students.FirstOrDefault(x=>x.Student_Number==s.Student_Number);
            if (new_s != null)
            {
                new_s.Student_Number = s.Student_Number;
                new_s.Student_Name = s.Student_Name;
                new_s.Student_Surname = s.Student_Surname;
                c.SaveChanges();
            }
            
            return RedirectToAction("Student_Index");
        }
        [HttpGet]
        public ActionResult Contains_Ex()
        {

            string aranan = null;

            return View(aranan);
        }
        [HttpPost]
        public ActionResult Contains_Ex(string aranan)
        {
            var degerler = from item in c.Students
                           where item.Student_Name.Contains(aranan) || item.Student_Surname.Contains(aranan)
                           select item.Student_Name;


            return View(degerler.ToList());
        }
    }
}

LINQ-STD/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LINQ-STD/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LINQ-STD/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

LINQ-STD/Views/Lesson/Add_Lesson.cshtml
@model LINQ_STD.Models.Lesson
@{
    ViewBag.Title = "Add_Lesson";
    Layout = "~/Views/View.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">  
    LESSON NAME
    @Html.TextBoxFor(x=> x.Lesson_Name, new {@class="form-control"});
    <button type="submit" class="btn btn-success">CREATE</button>
</form>

LINQ-STD/Views/Lesson/Lesson_Index.cshtml
@model List<LINQ_STD.Models.Lesson>
@{
    ViewBag.Title = "Lesson_Index";
    Layout = "~/Views/View.cshtml";
}

<table class="table table-striped table-hover">
    <tr>
        <th class="col">LESSON ID</th>
        <th class="col">LESSON NAME</th>
        <th class="col">DELETE</th>
        <th class="col">UPDATE</th>


    </tr>

    @foreach (var x in Model)
    {
        <tr >
            <th class="col">@x.Lesson_Id</th>
            <th class="col">@x.Lesson_Name</th>
            <th class="col"><a class="btn btn-danger" href="/Lesson/Delete_Lesson/@x.Lesson_Id">DELETE</a></th>
            <th class="col"><a class="btn btn-success" href="/Lesson/Update_Lesson/@x.Lesson_Id">UPDATE</a></th>



        </tr>
    }
</table>

LINQ-STD/Views/Lesson/Update_Lesson.cshtml
@model LINQ_STD.Models.Lesson
@{
    ViewBag.Title = "Update_Lesson";
    Layout = "~/Views/View.cshtml";
}

@using (Html.BeginForm("Update_Lesson", "Lesson", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div>
        @Html.HiddenFor(model => model.Lesson_Id)
        <br />
        LESSON NAME
        @Html.TextBoxFor(x => x.Lesson_Name, new { @class = "form-control" });
        <br />
        <button type="submit" class="btn btn-success">UPDATE</button>
    </div>
}

LINQ-STD/Views/Note/Add_Note.cshtml
@model LINQ_STD.Models.Note
@{
    ViewBag.Title = "Add_Note";
    Layout = "~/Views/View.cshtml";
}

@using (Html.BeginForm("Add_Note", "Note", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div>
        NOTE 1
        @Html.TextBoxFor(x => x.Note_1, new {@class="form-control"})
        <br />
        NOTE 2
        @Html.TextBoxFor(x => x.Note_2, new {@class="form-control"})
        STUDENT
        @Html.TextBoxFor(x => x.Student_Number, new {@class="form-control"})
        LESSON
        @Html.TextBoxFor(x => x.Lesson_Id, new {@class="form-control"})
        <button class="btn btn-success" type="submit"> CREATE</button>

    </div>


}

LINQ-STD/Views/Note/Note_Index.cshtml
@model List<LINQ_STD.Models.Note>
@{
    ViewBag.Title = "Note_Index";
    Layout = "~/Views/View.cshtml";
}

<table class="table table-striped table-hover">
    <tr>
        <th>ID</th>
        <th>ABAOT STUDENT</th>
        <th>ABAOT LESSON</th>
        <th>NOTE 1</th>
        <th>NOTE 2</th>
        <th>AVARAGE</th>
        <th>STATU</th>
        <th>DELETE</th>
        <th>UPDATE</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <th>@x.Note_Id</th>
            <th>@x.Student.Student_Name @x.Student.Student_Surname</th>
            <th>@x.Lesson.Lesson_Name</th>
            <th>@x.Note_1</th>
            <th>@x.Note_2</th>
            <th>@x.Note_Average</th>
            <th>@x.Statu</th>
            <th><a href="/Note/Delete_Note/@x.Note_Id" class="btn btn-danger">DELETE</a></th>
            <th><a href="/Note/Update_Note/@x.Note_Id" class="btn btn-success">UPDATE</a></th>

            

        </tr>
    }
</table>

LINQ-STD/Views/Note/Update_Note.cshtml
@model LINQ_STD.Models.Note
@{
    ViewBag.Title = "Update_Note";
    Layout = "~/Views/View.cshtml";
}

@using (Html.BeginForm("Update_Note", "Note", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(x => x.Note_Id);

    <div>
        NOTE 1
        @Html.TextBoxFor(x => x.Note_1, new { @class = "form-control" })
        <br />
        NOTE 2
        @Html.TextBoxFor(x => x.Note_2, new { @class = "form-control" })
        STUDENT
        @Html.TextBoxFor(x => x.Student_Number, new { @class = "form-control" })
        LESSON
        @Html.TextBoxFor(x => x.Lesson_Id, new { @class = "form-control" })
        <button class="btn btn-success" type="submit"> CREATE</button>
    </div>

}

LINQ-STD/Views/OtherWorks/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/View.cshtml";
}

<div>@ViewBag.v1</div>

LINQ-STD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LINQ-STD/Views/Student/Add_Student.cshtml
@model LINQ_STD.Models.Student
@{
    ViewBag.Title = "Add_Student";
    Layout = "~/Views/View.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
    <br />
    STUDENT NAME
    @Html.TextBoxFor(s => s.Student_Name,new { @class = "form-control" })
    <br />
    STUDENT SURNAME
    @Html.TextBoxFor(s => s.Student_Surname,new { @class = "form-control" })
    <br />
    <button type="submit" class="btn btn-success">CREAT</button> 
</form>

LINQ-STD/Views/Student/Contains_Ex.cshtml
@model List<LINQ_STD.Models.Student>
@{
    ViewBag.Title = "Contains_Ex";
    Layout = "~/Views/View.cshtml";
}

<h2>Contains_Exempla</h2>
<form action="/Student/Contains_Ex" method="POST">
    <div>
        <input name="aranan" type="text" value="@Request["aranan"]" class="text-success form-control">
    </div>
    <button type="submit">SEARCH</button>
</form>
@if (Model != null)
{

    <table class="table table-striped">
        <tr>
            <th class="col">NUMBER</th>
            <th>NAME-SURNAME</th>

        </tr>

        @foreach (var x in Model)
        {
            <tr>
                <th class="col">@x.Student_Number</th>
                <th class="col">@x.Student_Name @x.Student_Surname</th>

            </tr>

        }

    </table>
}

LINQ-STD/Views/Student/Student_Index.cshtml
@model List<LINQ_STD.Models.Student>
@{
    ViewBag.Title = "Student_Index";
    Layout = "~/Views/View.cshtml";
}


<table class="table table-striped table-hover">
    <tr>
        <th scope="col">NUMBER</th>
        <th scope="col">NAME</th>
        <th scope="col">SURNAME</th>
        <th scope="col">DELETE</th>
        <th scope="col">UPDATE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>

            <th>@x.Student_Number</th>
            <th>@x.Student_Name</th>
            <th>@x.Student_Surname</th>
            <th> <a href="Delete_Student/@x.Student_Number" class="btn btn-danger">DELETE</a></th>
            <th> <a href="Update_Student/@x.Student_Number" class="btn btn-success">UPDATE</a></th>
            
        </tr>
    }
</table>

LINQ-STD/Views/Student/Update_Student.cshtml
@model LINQ_STD.Models.Student
@{
    ViewBag.Title = "Update_Student";
    Layout = "~/Views/View.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
    @Html.HiddenFor(model => model.Student_Number)
    <br />
    STUDENT NAME
    @Html.TextBoxFor(x => x.Student_Name, new { @class = "form-control" });
    <br />
    STUDENT SURNAME
    @Html.TextBoxFor(x => x.Student_Surname, new { @class = "form-control" });
    <br />
    <button type="submit" class="btn btn-success">CREAT</button>
</form>

LINQ-STD/Views/View.cshtml
@{
    Layout = null;
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <div class="row">
        <div class="list-group list-group-flush col-lg-2">
            <a href="/Student/Student_Index" class="list-group-item list-group-item-success"> STUDENT-LIST</a>
            <a href="/Student/Add_Student" class="list-group-item list-group-item-success"> STUDENT-ADD</a>
            <a href="/Lesson/Lesson_Index" class="list-group-item list-group-item-success"> LESSON-LIST</a>
            <a href="/Lesson/Add_Lesson" class="list-group-item list-group-item-success"> LESSON-ADD</a>
            <a href="/Note/Note_Index" class="list-group-item list-group-item-success"> NOTE-LIST</a>
            <a href="/Note/Add_Note" class="list-group-item list-group-item-success"> NOTE-ADD</a>


        </div>
        <div class="col-lg-10">
            @RenderBody()
        </div>
    </div>
</body>
</html>